version: "3.1"

services:
    app:
        container_name: invest_insight_app
        build: ./apps/app
        ports:
            - '8080:8080'
        volumes:
            - ./apps/app:/invest-insight/app
            - /invest-insight/app/node_modules
        depends_on:
            - api
    api:
        container_name: invest_insight_api
        build: ./apps/api
        ports:
            - '3000:3000'
        volumes:
            - ./apps/api:/invest-insight/api
            - /invest-insight/api/node_modules
        links:
            - redis
        depends_on:
            - mongo-server
    redis:
        container_name: invest_insight_cache
        image: redis:latest
        expose:
            - "6379"
    mongo-server:
        container_name: invest_insight_db
        image: mongo:latest
        restart: always
        volumes: 
            - ./iiData:/data/db
        environment:
            - MONGO_INITDB_DATABASE= InvestInsight
        ports:
            - 27017:27017
